# Generated by Django 3.2.8 on 2021-11-11 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20211111_1715'),
    ]

    operations = [
        migrations.RenameField(
            model_name='Comments',
            old_name='auction',
            new_name='listings',
        ),
    ]
