# Generated by Django 3.2.8 on 2021-11-12 03:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_rename_auction_comments_listings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionlist',
            old_name='discription',
            new_name='description',
        ),
        migrations.AddField(
            model_name='auctionlist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auctionlist',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
