# Generated by Django 3.2.8 on 2021-11-20 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_comments_comment_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlist',
            name='starting_price',
            field=models.IntegerField(default=0),
        ),
    ]
